spring.application.name=gym-management

# Database
spring.datasource.url=jdbc:postgresql://64.71.152.28/demodatabase?currentSchema=gym_management
spring.datasource.username=demouser
spring.datasource.password=IPRQD2M2zE12
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
app.jwt.expiration=86400000

# CORS
app.cors.allowed-origins=http://localhost:5173

server.port=8080
